services:
  client:
    image: ghcr.io/ilyasa1211/game-tictactoe-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  server:
    image: ghcr.io/ilyasa1211/game-tictactoe-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
